//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelCinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class film
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public film()
        {
            this.genre_film = new HashSet<genre_film>();
            this.participations = new HashSet<participation>();
            this.seances = new HashSet<seance>();
        }
    
        public int id { get; private set; }
        public string titre { get; private set; }
        public Nullable<int> ranking { get; private set; }
        public string description { get; private set; }
        public int annee_parution { get; private set; }
        public int duree { get; private set; }
        public Nullable<double> rating { get; private set; }
        public Nullable<double> revenu { get; private set; }
        public Nullable<int> votes { get; private set; }
        public Nullable<int> metascore { get; private set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<genre_film> genre_film { get; private set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<participation> participations { get; private set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<seance> seances { get; private set; }
    }
}
