//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelCinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class film
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public film()
        {
            this.genre_film = new HashSet<genre_film>();
            this.participations = new HashSet<participation>();
            this.seances = new HashSet<seance>();
        }
    
        public int id { get; set; }
        public string titre { get; set; }
        public int ranking { get; set; }
        public string description { get; set; }
        public int annee_parution { get; set; }
        public int duree { get; set; }
        public double rating { get; set; }
        public Nullable<double> revenu { get; set; }
        public Nullable<int> votes { get; set; }
        public Nullable<int> metascore { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        private ICollection<genre_film> genre_film { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        private ICollection<participation> participations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        private ICollection<seance> seances { get; set; }
    }
}
