//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelCinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class genre_film
    {
        private int id { get; set; }
        private int genre_id { get; set; }
        private int film_id { get; set; }
    
        private film film { get; set; }
        private genre genre { get; set; }
    }
}
