//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelCinema.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cinema_dbEntities : DbContext
    {
        public cinema_dbEntities()
            : base("name=cinema_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cinema> cinemas { get; set; }
        public virtual DbSet<contact_info> contact_info { get; set; }
        public virtual DbSet<film> films { get; set; }
        public virtual DbSet<genre> genres { get; set; }
        public virtual DbSet<genre_film> genre_film { get; set; }
        public virtual DbSet<participant> participants { get; set; }
        public virtual DbSet<participation> participations { get; set; }
        public virtual DbSet<role_participant> role_participant { get; set; }
        public virtual DbSet<salle> salles { get; set; }
        public virtual DbSet<salle_status> salle_status { get; set; }
        public virtual DbSet<seance> seances { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<user_status> user_status { get; set; }
        public virtual DbSet<user_type> user_type { get; set; }
    }
}
