//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelCinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class participation
    {
        public int id { get; private set; }
        public int participant_id { get; private set; }
        public int role_id { get; private set; }
        public int film_id { get; private set; }
    
        public virtual film film { get; private set; }
        public virtual participant participant { get; private set; }
        public virtual role_participant role_participant { get; private set; }
    }
}
